name: Meu Workflow Básico

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # A cada hora

jobs:
  exemplo-job:
    runs-on: ubuntu-latest

    steps:
      # Action existente: checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # Script personalizado
      - name: Executar script personalizado
        run: |
          echo "Olá! Este é um script personalizado."
          echo "Data e hora atual:"
          date
